apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-backend-sa
  annotations:
    iam.gke.io/gcp-service-account: rag-backend-sa@btoproject-486405-486604.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-frontend-sa
  annotations:
    iam.gke.io/gcp-service-account: rag-frontend-sa@btoproject-486405-486604.iam.gserviceaccount.com
